# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :compressed

# Site settings
title:             "LND PR Review Club"
description:       "A bi-weekly review club for LND PRs"
author:            "LND PR Review Club contributors"
meeting_time:      "TBD"
meeting_day:       "TBD"
meeting_location:  '#review-club channel on <a href="https://lightning.engineering/slack.html">LND Developer Community Slack</a>'
future: true
url: https://lnd.reviews
twitter_username: 
twitter:
  card: summary
  username: 

# Exclude from processing
exclude:
   - CONTRIBUTING.md
   - Gemfile
   - Gemfile.lock
   - Makefile
   - README.md
   - Rakefile
   - test/

defaults:
  - scope:
      path: ""  ## all pages
    values:
      image: /assets/img/twitter_card.png

permalink: :title
